### PR TITLE
Fix backend

### LINKED ISSUE #33: Fix backend data access layer
- Currently some things like updates are very hacky

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Closes #33 

## Note

1. Soft-Deletion is re-enabled
2. Used postman to test. Postman collection can be found [here](https://drive.google.com/file/d/1FQKiwyikn6J2jFQLsphhgIpzTAwCIXHW/view?usp=sharing).
3. Similar to AAC structure but adapted to Fluent.
4. Backend now only works with macOS version 12 and up.

## Test Done 

LIST: 
- [x] Documents without any annotations 
- [x] Documents with annotations but without text
- [x] Documents with annotations and text

READ:
- [x] Document without any annotations 
- [x] Document with annotations but without text
- [x] Document with annotations and text

CREATE:
- [x] Document without any annotations 
- [x] Document with annotations but without text
- [x] Document with annotations and text

UPDATE:
- [x] Document without any annotations 
- [x] Document with annotations but without text
- [x] Document with annotations and text

DELETE:
- [x] Document without any annotations 
- [x] Document with annotations but without text
- [x] Document with annotations and text

### CODE REVIEW

File: AnnotatoBackend/Sources/App/Models/Extensions/AnnotationEntity+CRUD.swift [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    }
+
+    func copyPropertiesOf(otherEntity: AnnotationEntity) {
+        precondition(id == otherEntity.id)
+
+        originX = otherEntity.originX
+        originY = otherEntity.originY
+        width = otherEntity.width
+        ownerId = otherEntity.ownerId
+        $documentEntity.id = otherEntity.$documentEntity.id
```
Comment (sivayogasubramanian) [inline AnnotatoBackend/Sources/App/Models/Extensions/AnnotationEntity+CRUD.swift:65]: Should we allow users to update this?

File: AnnotatoBackend/Sources/App/Models/Extensions/AnnotationTextEntity+CRUD.swift [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+    }
+
+    func copyPropertiesOf(otherEntity: AnnotationTextEntity) {
+        precondition(id == otherEntity.id)
+
+        type = otherEntity.type
+        content = otherEntity.content
+        height = otherEntity.height
+        order = otherEntity.order
+        $annotationEntity.id = otherEntity.$annotationEntity.id
```
Comment (sivayogasubramanian) [inline AnnotatoBackend/Sources/App/Models/Extensions/AnnotationTextEntity+CRUD.swift:33]: Same as the previous comment.

**Review by ganhongyao — APPROVED** [review]
LVVVGTM. This is great. Thanks! 🚀
